# utils functions for saving and loading sparse matrix
# author rovo98

from scipy.sparse import csr_matrix
import numpy as np


def save_sparse_csr(filename, array):
    """compressed and save the given np.array (csr sparse matrix) into a npz file.

    :type filename: str
    :type array: np.array
    :rtype None

    Arguments
        filename: the name of the file to save data.
        array : csr (compressed sparse row) matrix
    """
    np.savez_compressed(filename, data=array.data, indices=array.indices,
                        indptr=array.indptr, shape=array.shape)


def load_sparse_csr(filename):
    """Load csr matrix from the given npz file (generated by using save_sparse_csr() method before)

    :type filename: str
    :rtype csr_matrix

    Arguments
        filename: the name of the npz file to load data.
    """
    loader = np.load(filename)
    return csr_matrix((loader['data'], loader['indices'],
                       loader['indptr']), shape=loader['shape'])
